default:
  status: "adm" #"gis" # "dev"" or "prod" or "adm"
  app_name: "contratos"
  sepedatalake_adm:
    driver: 'Postgres'
    server: '10.238.107.182'
    uid: 'sepe_adm'
    pwd: '!sepe_adm!'
    port: 5432
    database: 'sepe'
  sepedatalake_prod:
    driver: 'Postgres'
    server: '10.238.107.182'
    uid: 'sepe_usr'
    pwd: '!Sepe%Usr!'
    port: 5432
    database: 'sepe'
  sepedatalake_dev:
    driver: 'Postgres'
    server: 'localhost'
    uid: 'sepe'
    pwd: '!sepe_usr!'
    port: 7777
    database: 'postgres'
  sepedatalake_gis:
    driver: 'Postgres'
    server: 'localhost'
    uid: 'sepe'
    pwd: '@!sepe!@'
    port: 7777
    database: 'postgres'